# Build stage
FROM maven:3.9.4-eclipse-temurin-21 AS build
WORKDIR /app
COPY pom.xml .
COPY src ./src
RUN mvn clean package -DskipTests

# Run stage
FROM eclipse-temurin:21-jre
WORKDIR /app
COPY --from=build /app/target/*.jar app.jar

EXPOSE 8000

CMD ["java", \
     "-Dspring.datasource.url=${SPRING_DATASOURCE_URL}", \
     "-Dspring.datasource.username=${SPRING_DATASOURCE_USERNAME}", \
     "-Dspring.datasource.password=${SPRING_DATASOURCE_PASSWORD}", \
     "-jar", "app.jar"]