spring.application.name=DermaCode
server.port=8000
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect



SPRING_DATASOURCE_URL=jdbc:postgresql://ep-silent-recipe-ag7s9xbh.c-2.eu-central-1.pg.koyeb.app:5432/koyebdb
SPRING_DATASOURCE_USERNAME=koyeb-adm
SPRING_DATASOURCE_PASSWORD=npg_XsHBKt57nuxi